import bcrypt from "bcrypt";
import pool from "../lib/db"; // Uses the shared DB pool from /lib/db.js to prevent connection leaks

export default async function handler(req, res) {
  // Only allow POST requests to ensure registration data is sent in the body
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Destructure with a fallback to an empty object to avoid crashes if body is null
  const { username, password } = req.body || {};

  // Basic validation: both fields are required to create an account
  if (!username || !password) {
    return res.status(400).json({ error: "Missing username or password" });
  }

  try {
    /**
     * Hash the password with a salt round (cost factor) of 10.
     * This performs 2^10 (1024) iterations, making brute-force attacks much harder.
     */
    const hash = await bcrypt.hash(password, 10);

    // Save the new user record; the ID is usually auto-generated by the DB (SERIAL/IDENTITY)
    await pool.query(
      "INSERT INTO users (username, password_hash) VALUES ($1, $2)",
      [username, hash] // Parameters prevent SQL injection
    );

    // 201 Created: indicates successful resource creation
    return res.status(201).json({ ok: true });
  } catch (err) {
    console.error(err);

    /**
     * PostgreSQL Error Code 23505: Unique Violation
     * Triggered if the 'username' already exists in the table.
     */
    if (err.code === "23505") {
      return res.status(409).json({ error: "Username already exists" });
    }

    // Standard fallback for unexpected database or server errors
    return res.status(500).json({ error: "Server error" });
  }
}
